ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS age_group VARCHAR(60) NULL AFTER name,
  ADD COLUMN IF NOT EXISTS season_year VARCHAR(30) NULL AFTER age_group,
  ADD COLUMN IF NOT EXISTS level VARCHAR(80) NULL AFTER season_year,
  ADD COLUMN IF NOT EXISTS home_rink VARCHAR(160) NULL AFTER level,
  ADD COLUMN IF NOT EXISTS city VARCHAR(120) NULL AFTER home_rink,
  ADD COLUMN IF NOT EXISTS team_notes TEXT NULL AFTER city,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
